name: pitchupfluttersample
description: Sample on how to implement a guitar tuning app in Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pitch_detector_dart: ^0.0.1
  pitchupdart: ^0.0.1
  flutter_audio_capture: ^1.0.0
  permission_handler: ^10.2.0
  analyzer_plugin: ^0.11.2
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true