name: pitchupfluttersample
description: Sample on how to implement a guitar tuning app in Flutter

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '2.19.3'

dependencies:
  flutter:
    sdk: flutter

# #responsive
# argo: ^0.0.3

# #router
# go_router: ^3.0.4

# #UI
# google_fonts: ^2.3.1
# universal_html: ^2.0.8

# #DI 
# get_it: ^7.2.0

#management
#providerL ^6.0.2

  english_words: ^4.0.0
  provider: ^6.0.0
  persistent_bottom_nav_bar: ^5.0.2
  permission_handler: ^10.2.0
  analyzer_plugin: ^0.11.2
  pitchupdart: ^0.0.2
  flutter_audio_capture: ^1.1.4
  pitch_detector_dart: ^0.0.2
  shared_preferences: ^2.1.0
  argo: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

fonts:
  family: OpenSans
  asset: fonts/OpenSans-VariableFont_wdth,wght.ttf

flutter:
  uses-material-design: true
  assets:
    - assets/

  